# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f451c9a2a1908916d5e43505a4c92acceb5387dd820a5ff761d07c0a2652f986b91fce10f1a0484237edba9d4b1b0ece3431b63892e7f6fb3f57fa94bd75880

vagrant:
  secret_key_base: 9f451c9a2a1908916d5e43505a4c92acceb5387dd820a5ff761d07c0a2652f986b91fce10f1a0484237edba9d4b1b0ece3431b63892e7f6fb3f57fa94bd75880

test:
  secret_key_base: 42

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
